### ISSUE TITLE
5.1 User Management Class DIagram

### ISSUE THREAD

**Issue by PhutiSetoaba** [perrymatthew/cos301_team_ruby#15]

**Comment by kgothatsotlaka** [comment]
I looked at class diagram, I think the Admin Class will need CRUD methods for a user and CRUD methods for an event

**Comment by vtwigge1000** [comment]
I've added the CRUD methods to admin as well as a deleteProfileRequest() method to User. You guys can check it out again and see if you're happy.

**Comment by kgothatsotlaka** [comment]
I've checked the class diagram, it was really good since I was able to work on the sequence diagram from it. Don't forget to review the sequence diagram and let me know if there are any chances I'll need to do
