### ISSUE TITLE
5.4 User Management Sequence Diagram

### ISSUE THREAD

**Issue by kgothatsotlaka** [perrymatthew/cos301_team_ruby#19]

**Comment by kgothatsotlaka** [comment]
Hi, I am About to upload the Sequence diagram picture in the WIP branch. Please review it and get back to me because I'm really not sure with my work in this sequence diagram

**Comment by vtwigge1000** [comment]
Hi Tlaka. Just check some of the spelling: UserData Valide, useData, IsAmin, someFiled need to be corrected. 

Then the spec says "A user should not be created if the email specified in the request to create a user is already assocated with an existing user. This is done to ensure that if a user is already associated with the email address, the user is given access to his/her profile instead of creating a new user."

I'm not 100% sure but it seems like if a user wants to register but already exists, they should be directed (given access) to their profile.

What do you think?

**Comment by kgothatsotlaka** [comment]
You've got a point a point there,I agree with you because I even showed that in the activity diagram...I'll just edit the sequence diagram to include that



Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Victor Twigge <notifications@github.com> Date: 2017/03/07  20:00  (GMT+02:00) To: perrymatthew/cos301_team_ruby <cos301_team_ruby@noreply.github.com> Cc: Mankgwanyane Tlaka <u14351872@tuks.co.za>, Assign <assign@noreply.github.com> Subject: Re: [perrymatthew/cos301_team_ruby] 5.4 User Management Sequence Diagram (#19) 
Hi Tlaka. Just check some of the spelling: UserData Valide, useData, IsAmin, someFiled need to be corrected.
Then the spec says "A user should not be created if the email specified in the request to create a user is already assocated with an existing user. This is done to ensure that if a user is already associated with the email address, the user is given access to his/her profile instead of creating a new user."
I'm not 100% sure but it seems like if a user wants to register but already exists, they should be directed (given access) to their profile.
What do you think?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/perrymatthew/cos301_team_ruby","title":"perrymatthew/cos301_team_ruby","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/perrymatthew/cos301_team_ruby"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vtwigge1000 in #19: Hi Tlaka. Just check some of the spelling: UserData Valide, useData, IsAmin, someFiled need to be corrected. \r\n\r\nThen the spec says \"A user should not be created if the email specified in the request to create a user is already assocated with an existing user. This is done to ensure that if a user is already associated with the email address, the user is given access to his/her profile instead of creating a new user.\"\r\n\r\nI'm not 100% sure but it seems like if a user wants to register but already exists, they should be directed (given access) to their profile.\r\n\r\nWhat do you think?"}],"action":{"name":"View Issue","url":"https://github.com/perrymatthew/cos301_team_ruby/issues/19#issuecomment-284804252"}}}
-- 
This message and attachments are subject to a disclaimer. Please refer to 
http://www.it.up.ac.za/documentation/governance/disclaimer/ for full 
details.

**Comment by kgothatsotlaka** [comment]
All mentioned changes are done
